feat: allow changing check interval
OutdatedGuy/internet_connection_checker_plus pull request #63
Opened 2024-11-25 14:17 UTC by GenixPL

- [feature] Added option to change check interval without creating a new instance.
- [fix] Corrected check interval's default value doc.

2024-11-25 14:25 UTC, GenixPL reviewed
i didnt wanna add new dependency ([fake_async](https://pub.dev/packages/fake_async)), or play on marginal time intervals, so the testing time has been extended by ~1.5s; can change if needed

2024-11-26 21:08 UTC, GenixPL commented
i have found a problem, working on a fix

2024-11-27 15:57 UTC, GenixPL reviewed
- the problem ive mentioned was in the project ive used the package (ive created a dumb mock spamming in my tests)... 🤦🏻‍♂️;
- ive noticed ive run it with wrong dart line length formatting, so that's corrected;
- ive fixed the tests (sry for submitting the first one without running the full suite, just mine); i needed the test binding, so ive moved my tests to a separate file (the binding was causing the real life test to fail);
- ive changed the name of the "setter" to better indicate that the timer will be reset (i was considering ignoring the set/reset if the value was the same as current, but ended up leaving it; it doesnt seem critical in any way - both ways seem reasonable)

sry again for submitting the pr before running full test suite

2024-12-12 19:28 UTC, OutdatedGuy commented
Hi @GenixPL, thanks for the PR. The implementation looks fine, but can you just give me a use case for this feature?

2024-12-12 20:14 UTC, OutdatedGuy requested changes
Looks good, just some minor nit-picks.

2024-12-12 20:14 UTC, OutdatedGuy commented on lib/src/internet_connection.dart
> +  /// Resets the [_timerHandle] in the process.
Change the doc comment to 

```dart
/// Updates the interval between connection checks to the given [duration] and
/// resets the connection checking timer.
```

2024-12-12 20:14 UTC, OutdatedGuy commented on lib/src/internet_connection.dart
> +  static const Duration _defaultCheckInterval = Duration(seconds: 10);
Please change doc comment to `The default check interval duration.` and also remove `Duration` declaration for `_defaultCheckInterval` as it gets inferred.

2024-12-12 20:14 UTC, OutdatedGuy commented on lib/src/internet_connection.dart
> +  /// Returns current [_checkInterval].
Please update comment to `Returns the current duration between connection checks.`

2024-12-12 20:14 UTC, OutdatedGuy commented on lib/src/internet_connection.dart
> +  }
Please convert this to expression body / function.

2024-12-12 20:14 UTC, OutdatedGuy commented on test/internet_connection_interval_change_test.dart
You can use the `setUp` function inside the `checkInterval` group to apply the Flutter binding for tests only in that group, like:

```dart
group('checkInterval', () {
  setUp(() {
      TestWidgetsFlutterBinding.ensureInitialized();
  });

  test('abc', () {});

  test('xyz', () {});
  
  // blah blah blah
});
```

2024-12-18 02:05 UTC, OutdatedGuy approved these changes
LGTM!

2024-12-18 02:11 UTC, merged